/*
 * This file was automatically generated by oml2-scaffold 2.12.0pre.147-8fe8-dirty
 * for map_experiment version 1.0.0.
 * 
 */

#define PACKAGE			"map_experiment"
#define VERSION			"1.0.0"

/* Provide compatibility with autoconf-generated config.h */
#define PACKAGE_NAME		PACKAGE
#define PACKAGE_TAR_NAME	PACKAGE
#define PACKAGE_VERSION		VERSION
#define PACKAGE_STRING PACKAGE_NAME " " PACKAGE_VERSION

