language: ruby
rvm:
  - 1.9.3-p484
install:
  - gem install net-ssh -v 2.9.2
  - gem install net-scp -v 1.2.1
  - gem install builder -v 3.2.2
  - gem install sinatra -v 1.4.7
script:
  - echo "Ping is at "`which ping`
  - ruby test/tests.rb
